##############################################################################
## \file vivado_wis.tcl
# \brief Creates a tcl script that copies the current values of the KotoDpm project's
# Linux OS environment variables. The purpose of the init.tcl output script is to
# properly establish the environment variables within the Windows version of Vivado without the need
# to first load Cygwin. This is useful because while using Vivado with Cygwin, Vivado runs roughly 2x slower.
## Dependencies: system_vivado.mk
## Author: Joshua Robinson
## Author Email: jorobin@umich.edu
## Last Updated: 12/22/2017
###############################################################################

# Get variables and procedures
source -quiet $::env(RUCKUS_DIR)/vivado_env_var.tcl
source -quiet $::env(RUCKUS_DIR)/vivado_proc.tcl

# Open the project
open_project -quiet ${VIVADO_PROJECT}

# create and open output file
set fp [open init_wis.tcl w]

########################################################
## Declare a list of Linux environment variables to copy to script
########################################################
# SLAC Project Variables
set     linuxVars "PRJ_PART"
lappend linuxVars "PROJECT"
lappend linuxVars "PRJ_VERSION"
lappend linuxVars "PROJ_DIR"
lappend linuxVars "TOP_DIR"
lappend linuxVars "IMAGES_DIR"
lappend linuxVars "OUT_DIR"
lappend linuxVars "SYN_DIR"
lappend linuxVars "IMPL_DIR"
lappend linuxVars "VIVADO_DIR"
lappend linuxVars "VIVADO_PROJECT"
lappend linuxVars "VIVADO_VERSION"
lappend linuxVars "RUCKUS_DIR"

# SLAC Vivado SDK Variables
lappend linuxVars "SDK_PRJ"
lappend linuxVars "SDK_LIB"
lappend linuxVars "SDK_ELF"

# Partial Reconfiguration Variables
lappend linuxVars "RECONFIG_CHECKPOINT"
lappend linuxVars "RECONFIG_ENDPOINT"
lappend linuxVars "RECONFIG_PBLOCK"

# Set GIT variables
lappend linuxVars "GIT_BYPASS"
lappend linuxVars "GIT_STATUS"
lappend linuxVars "GIT_HASH_LONG"
lappend linuxVars "GIT_HASH_SHORT"
lappend linuxVars "GIT_HASH_MSG"

# Set Non-Environmental variables
lappend linuxVars "vivado_cmd"

########################################################
## Copy list to tcl script
########################################################
# Create fp header
puts $fp "## Script Generation Information"

# Report Vivado version
puts $fp "# Vivado version: [version -short]"

# Report OS Information
puts $fp "# Script generated by mother OS: $tcl_platform(os) $tcl_platform(osVersion)"

# Report user information
puts $fp "# Generated by user: $tcl_platform(user)"

# Report general build string
puts $fp "# Build String: $env(BUILD_STRING)"

# write matching environment variables to file
puts $fp " "
puts $fp "# Set Environment Variables"
for {set i 0} {$i < [llength $linuxVars]} {incr i} {
    if {[info exists env([lindex $linuxVars $i])]} {
            puts $fp "set env([lindex $linuxVars $i]) $env([lindex $linuxVars $i])"
    }
}

# Close the file
close $fp

# Close the project
close_project
