.TH hlsExe 1 "May 2026" "v1.0" "HLS Command Manual"
.SH NAME
hlsExe \- runs the named component
configuration files

.SH SYNOPSIS
.B hlsExe [COMPONENT] [OPTIONS]

.SH DESCRIPTION
.TP
.B hlsExe
Provides a convenient way to execute the C simulation for the named component.


.SH COMPONENTS
The component to run, either just the component's name or the full file
specification(including the workspace
with wildcards.

.SH OPTIONS
.TP
\fB\-h, \-\-help\fR
Displays this message\

.TP
\fB\-w, \-\-workspace = \fIWORKSPACE\fR
The target workspace. Note that for existing projects, the workspace is almost
all the information that is needed.

.TP
\fB\-\-project = \fIPROJECT_FILE\fR
A project file is the standard method used by all the \fBhls\fR build utilities
of capturing the stable command line options in a file that can be saved in GIT.
For existing projects, the formality of a project file is not necessary. There
are simpler ways. Only for more complex projects is a project file needed. It is
mainly for consistency with other \fBhls\fR build utilities. Default is the
environment variable \fIHLSBS_PROJECT\fR.

.TP
\fB\-\-no-project
This prevents the use of any existing project file which may or may not exist.
Typically used when one wishes to specify all the relevant parameters (in this
utility these are \fBworkspace\fR and \fBconfigurations\fR and, possibly
\fBcomponents\fR if one wishes something other than the default. A common usage is
in one-off experimentation.

.TP
\fB\-\-All other options
All options that are specific to this component's C simulation

.SH Overriding with Command Line Options
The \fBhls\fR utilities are constructed so parameters can be specified at 3
levels depending on their permanency
    1. In the project file
    2. Indirectly overridden on the command line
    3. Directly overridden on the command line

The \fBproject file\fR is the most permanent and \fBoverriding\fR directly on
the command line the least. The disadvantage of overriding directly on the
command line is that, except for command recall, they are lost to history and even
then, they may be seen as just a random collection of options.

The third option offers something in between, allowing one to capture
command line options in a file.  This allows the options some degree of
permanency and, since it is a file, it can be given a meaningful name. The
disadvantage is, due the complexity in some utilities, not all options offered
in the project file are available.

The command line syntax is \fI@<MY_OPTIONS>\fR, i.e. the file name preceded by
an \fB@\fR. The file is trivially formatted, one option (no spaces) per line.
See the example below.

.SH Examples:

  Example 1
  $ hlsExe my_csim --no_project --workspace=$MY_PROJECT/ws/{vitis_version}
           --ntests=5
    Runs the C simulation \fBmy_csim\fR from the specified workspace. The
    \fB--ntests=5\fR will override any setting of \fBntests\fR found in its
    corresponding configuration file


  Example 2
  $ hlsExe my_csim
  Runs the C simulation \fBmy_csim\fR using the workspace found in the
  project file


  Example 3
  $ hlsExe @MyCsimOption.txt

  Assuming \fBMyCsimOptions.txt\fR contains
       my_csim
       --no_project
       --workspace=$MY_PROJECT/ws/{vitis_version}

  This duplicates Example 1.  The ordering is somewhat important, but
  only in the sense that the last instance supersedes previous ones.
  This is handy for one-off experimentation.

.SH AUTHOR
Written by JJRussell
